#!/usr/bin/env python3

import argparse
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

try:
    import yaml
except ModuleNotFoundError:
    raise SystemExit(
        'PyYAML not found. Install it with one of:\n'
        '  python3 -m pip install pyyaml  # installs for the python3 in your PATH\n'
        '  brew install pyyaml            # macOS\n'
        '  apt install python3-yaml       # Debian/Ubuntu\n'
        '  dnf install python3-pyyaml    # Fedora/RHEL'
    )


class ConfigError(Exception):
    pass


class _DuplicateKeyLoader(yaml.SafeLoader):
    pass


def _construct_mapping(loader, node):
    loader.flatten_mapping(node)
    pairs = loader.construct_pairs(node, deep=True)
    keys_seen = {}
    for key, _ in pairs:
        if key in keys_seen:
            raise ConfigError(
                'duplicate key "{}" at line {}'.format(key, node.start_mark.line + 1)
            )
        keys_seen[key] = True
    return dict(pairs)


_DuplicateKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
    _construct_mapping,
)

special_key_chars: List[str] = ['~']

template: str = (
    '''#
# Generated by generate_plugin.py.
#
# init.tmux: called by plugin.sh.tmux to initialize the plugin.
#

display -p '[tmux-which-key] Loading plugin ...'

#
# User options
#

{user_options}

#
# Custom variables
#

{custom_variables}

#
# Menus
#

{menus}
'''

    # We define custom actions as command aliases because they run directly in
    # tmux, which is much faster than using shell commands. They're also
    # expanded when parsed--unlike options, which need to be expanded at
    # execution--so they can be used in key bindings.
    #
    # Define the root menu entrypoint as an alias:
    #  - It must be defined after the root menu so it can be expanded
    #  - Aliases can't reference other aliases, so we expand the @wk_cmd_show
    #  option as a format instead
    #  - We don't define it as an option because bind-key doesn't support
    #  formats and `run-shell "bind-key ${...}"` doesn't preserve quotes
    #  correctly
    '''
#
# Macros
#

set -gF @wk_cmd_show \\
"display-menu \\
-x '#{{@wk_cfg_pos_x}}' \\
-y '#{{@wk_cfg_pos_y}}' \\
-T '#[#{{@wk_cfg_title_style}}]#[#{{@wk_cfg_title_prefix_style}}]#{{@wk_cfg_title_prefix}}#[#{{@wk_cfg_title_style}}]'"

{macros}

#
# Keybindings
#

{keybindings}

display -p '[tmux-which-key] Done'
''')


def add_quotes(s: str) -> str:
    '''Wraps s in quotes if it has any whitespace or special chars, escaping
    existing double-quotes.'''
    if all(c.isalnum() or c in ['-', '_'] for c in s):
        return s

    return '"{}"'.format(s.replace('"', '\\"'))


@dataclass
class Keybindings(object):
    prefix_table: str
    root_table: str = ''

    def __post_init__(self):
        if not self.prefix_table:
            raise ConfigError('keybindings.prefix_table is required')

    def __str__(self) -> str:
        # `bind-key` doesn't support formats, so we use `run-shell` to inject
        # the config values.
        return '\n\n'.join(['\n'.join([
            'display -p "[tmux-which-key] Binding {table} table key to #{{@wk_cfg_key_{table}_table}} ..."'.format(
                table=table),
            'run-shell "tmux bind-key -T{table} #{{@wk_cfg_key_{table}_table}} show-wk-menu-root"'.format(
                table=table)
        ]) for table in [
            'root',
            'prefix'
        ] if self.__getattribute__('{}_table'.format(table))])


@dataclass
class Position(object):
    x: str
    y: str

    def __post_init__(self):
        if self.x not in ['C', 'R', 'P', 'M', 'W']:
            raise ConfigError(
                'position.x must be one of C, R, P, M, W — got "{}"'.format(self.x)
            )
        if self.y not in ['C', 'P', 'M', 'W', 'S']:
            raise ConfigError(
                'position.y must be one of C, P, M, W, S — got "{}"'.format(self.y)
            )


@dataclass
class UserOption(object):
    name: str
    value: str

    def __str__(self) -> str:
        return 'set -g @{} "{}"'.format(self.name, self.value)


@dataclass
class CustomVariable(object):
    name: str
    value: str

    def __str__(self) -> str:
        # Sets the env var as hidden (-h) so it's only available to tmux
        # processes.
        return 'setenv -h {} "{}"'.format(self.name, self.value)


@dataclass
class Macro(object):
    index: int
    name: str
    commands: List[str]

    def __post_init__(self):
        if not all(c.isalnum() or c in ['-', '_'] for c in self.name):
            raise ConfigError('macro has invalid name: "{}". Names must be alphanumeric with - or _'.format(self.name))
        if not isinstance(self.commands, list):
            raise ConfigError('macro "{}" must have a commands list'.format(self.name))

    def __str__(self) -> str:
        return "set -gF command-alias[{}] {}=\\\n'{}'".format(
            self.index, self.name, ' ; \\\n'.join(self.commands),
        )


@dataclass
class MenuItem(object):
    parent_menu_id: Optional[str] = None
    name: Optional[str] = None
    key: Optional[str] = None
    menu: Optional[List[dict]] = None
    macro: Optional[str] = None
    command: Optional[str] = None
    separator: Optional[bool] = False
    transient: bool = False

    def __post_init__(
            self,
    ):
        if not self.separator:
            if not self.name:
                raise ConfigError('item is missing a name')
            self.name = add_quotes(self.name)

            if not self.key:
                raise ConfigError('item "{}" is missing a key'.format(self.name))
            # Escape special key characters.
            has_special_key_char = False
            for k in special_key_chars:
                if k in self.key:
                    has_special_key_char = True
                    self.key = self.key.replace(k, '\\{}'.format(k))

            if has_special_key_char:
                self.key = '"{}"'.format(self.key)

        if self.menu:
            if not self.name or self.macro or self.command:
                raise ConfigError('submenu item must have only a name, key, and menu')
            if len(self.menu) == 0:
                raise ConfigError('submenu "{}" has no items'.format(self.name))
            # Assign an alphanumeric menu ID for use in tmux user options.
            self.menu_id = ''.join(
                [c for c in self.name if c.isalnum() or c in ['-', '_']]).lower()
            self.command = 'show-wk-menu #{{@wk_menu_{}}}'.format(
                self.menu_id)
        elif self.macro:
            if self.menu or self.command:
                raise ConfigError('item "{}" must have only one of: menu, macro, command'.format(self.name))
            self.command = self.macro
        elif self.command:
            if self.menu or self.macro:
                raise ConfigError('item "{}" must have only one of: menu, macro, command'.format(self.name))
        elif self.separator:
            if self.key or self.menu or self.macro or self.command:
                raise ConfigError('separator items must not have other fields')
        else:
            raise ConfigError('item "{}" must have one of: menu, macro, command'.format(self.name))

        if self.transient:
            if not self.parent_menu_id:
                raise ConfigError('transient item "{}" has no parent menu'.format(self.name))
            self.command = '{} ; show-wk-menu #{{@wk_menu_{}}}'.format(
                self.command, self.parent_menu_id)

        if self.command:
            self.command = add_quotes(self.command)

    def __str__(self) -> str:
        if self.separator:
            return '""'

        return '{} {} {}'.format(self.name, self.key, self.command)


@dataclass
class Menu(object):
    name: str
    id: str
    items: List[MenuItem]

    def __str__(self) -> str:
        return "set -g @wk_menu_{} \\\n'{}'".format(self.id, ' \\\n'.join(map(str, self.items)))


class Config(object):
    def __init__(
        self,
        command_alias_start_index: int,
        keybindings: dict,
        items: List[dict],
        title: Optional[dict] = None,
        position: Optional[dict] = None,
        custom_variables: Optional[List[dict]] = None,
        macros: Optional[List[dict]] = None,
    ) -> None:
        if command_alias_start_index < 200:
            raise ConfigError(
                'command_alias_start_index must be >= 200 (got {}). '
                'Indices 100-199 are reserved by tmux examples.'.format(command_alias_start_index)
            )
        self.command_alias_start_index = command_alias_start_index

        title = title or {}
        title = {
            'style': title.get('style', 'align=centre,bold'),
            'prefix': title.get('prefix', 'tmux'),
            'prefix_style': title.get('prefix_style', 'fg=green,align=centre,bold'),
        }
        position = position or {'x': 'R', 'y': 'P'}
        custom_variables = custom_variables or []
        macros = macros or []

        self.keybindings = Keybindings(**keybindings)
        self.title = title
        self.position = Position(**position)

        opts = {
            'wk_cfg_key_root_table': self.keybindings.root_table,
            'wk_cfg_key_prefix_table': self.keybindings.prefix_table,
            'wk_cfg_title_style': title['style'],
            'wk_cfg_title_prefix': title['prefix'],
            'wk_cfg_title_prefix_style': title['prefix_style'],
            'wk_cfg_pos_x': self.position.x,
            'wk_cfg_pos_y': self.position.y,
        }
        self.user_options = [UserOption(name=k, value=opts[k])
                             for k in opts if opts[k]]

        self.custom_variables = [CustomVariable(
            v['name'], v['value']) for v in custom_variables]

        macros = [{
            'name': 'show-wk-menu',
            'commands': ['#{@wk_cmd_show}']
        }, {
            'name': 'show-wk-menu-root',
            'commands': ['#{@wk_cmd_show} #{@wk_menu_root}']
        }] + macros
        self.macros = [Macro(self.command_alias_start_index+i, name=m['name'], commands=m['commands'])
                       for i, m in enumerate(macros)]

        self.macro_names = set([m.name for m in self.macros])
        self.menu_ids = set()
        self.menus = []
        self.register_menu('root', 'root', items)

    def register_menu(self, name: str, id: str, items: List[dict]):
        menu = Menu(name, id, items=[])
        if menu.id in self.menu_ids:
            raise ConfigError(
                'menu ID collision: "{}" and another menu both produce the ID "{}". '
                'Rename one of them.'.format(name, menu.id)
            )
        self.menu_ids.add(menu.id)

        mapped_keys = set()
        for item in items:
            item = MenuItem(parent_menu_id=id, **item)
            if item.menu:
                assert item.name
                self.register_menu(item.name, item.menu_id, item.menu)
            elif item.macro:
                if item.macro not in self.macro_names:
                    raise ConfigError(
                        'item "{}" references unknown macro "{}". '
                        'Defined macros: {}'.format(item.name, item.macro, ', '.join(sorted(self.macro_names)))
                    )

            if item.key:
                if item.key in mapped_keys:
                    raise ConfigError(
                        'duplicate key "{}" in menu "{}"'.format(item.key, name)
                    )
            mapped_keys.add(item.key)

            menu.items.append(item)

        self.menus.append(menu)
        return menu

    def __str__(self) -> str:
        return template.format(
            user_options='\n'.join(map(str, self.user_options)),
            custom_variables='\n'.join(map(str, self.custom_variables)),
            menus='\n\n'.join(map(str, self.menus)),
            macros='\n\n'.join(map(str, self.macros)),
            keybindings=self.keybindings,
        )


def main() -> int:
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "config_file", help="The plugin config file", type=Path)
    parser.add_argument(
        "output_file", nargs='?', help="The file where plugin init script will be written", type=Path)
    parser.add_argument(
        "--validate", action="store_true",
        help="Validate config only — do not write output")
    args = parser.parse_args()

    if not args.validate and args.output_file is None:
        parser.error("output_file is required unless --validate is set")

    try:
        logging.info('Reading configuration ...')
        with open(args.config_file) as config_file:
            data = yaml.load(config_file, Loader=_DuplicateKeyLoader)
        if not isinstance(data, dict):
            raise ConfigError('config file must be a YAML mapping at the top level')

        logging.info('Building menu ...')
        config = Config(**data)

    except ConfigError as e:
        raise SystemExit('[tmux-which-key] Config error: {}'.format(e))
    except TypeError as e:
        raise SystemExit('[tmux-which-key] Config error: unexpected field — {}'.format(e))

    if args.validate:
        logging.info('Config is valid')
        return 0

    out = str(config)
    with open(args.output_file, 'w+') as output_file:
        output_file.write(out)

    logging.info('Done')
    return 0


if __name__ == '__main__':
    sys.exit(main())
