#!/usr/bin/env python3

import argparse
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

try:
    import yaml
except ModuleNotFoundError:
    raise SystemExit(
        'PyYAML not found. Install it with one of:\n'
        '  python3 -m pip install pyyaml  # installs for the python3 in your PATH\n'
        '  brew install pyyaml            # macOS\n'
        '  apt install python3-yaml       # Debian/Ubuntu\n'
        '  dnf install python3-pyyaml    # Fedora/RHEL'
    )


class ConfigError(Exception):
    pass


def require_mapping(value, path: str) -> dict:
    if not isinstance(value, dict):
        raise ConfigError('{} must be a mapping'.format(path))
    return value


def require_fields(value: dict, path: str, fields: List[str]) -> None:
    missing = [field for field in fields if field not in value]
    if missing:
        raise ConfigError('{} is missing required field(s): {}'.format(
            path,
            ', '.join(missing),
        ))


def reject_unknown_fields(value: dict, path: str, fields: List[str]) -> None:
    unknown = [field for field in value if field not in fields]
    if unknown:
        raise ConfigError('{} has unexpected field(s): {}'.format(
            path,
            ', '.join(unknown),
        ))


class _DuplicateKeyLoader(yaml.SafeLoader):
    pass


def _construct_mapping(loader, node):
    loader.flatten_mapping(node)
    pairs = loader.construct_pairs(node, deep=True)
    keys_seen = {}
    for key, _ in pairs:
        if key in keys_seen:
            raise ConfigError(
                'duplicate key "{}" at line {}'.format(key, node.start_mark.line + 1)
            )
        keys_seen[key] = True
    return dict(pairs)


_DuplicateKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
    _construct_mapping,
)

# Macro names the plugin defines for itself. The menu keybindings invoke these,
# so a user macro reusing one of these names would silently shadow it (two
# command-alias entries with the same name) and break the menu.
reserved_macro_names: List[str] = ['show-wk-menu', 'show-wk-menu-root']


def _is_safe_char(c: str) -> bool:
    '''True for characters safe to emit unquoted in tmux: alphanumerics, - and _.'''
    return c.isalnum() or c in '-_'


def escape_tmux_string(s: str) -> str:
    '''Escape a string for use inside a tmux double-quoted string.'''
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def quote_tmux_string(s: str) -> str:
    '''Quote a string as one tmux command argument.'''
    return '"{}"'.format(escape_tmux_string(s))

template: str = (
    '''#
# Generated by plugin/build.py.
#
# init.tmux: called by plugin.sh.tmux to initialize the plugin.
#

display -p '[tmux-which-key] Loading plugin ...'

#
# User options
#

{user_options}

#
# Custom variables
#

{custom_variables}

#
# Menus
#

{menus}
'''

    # We define custom actions as command aliases because they run directly in
    # tmux, which is much faster than using shell commands. They're also
    # expanded when parsed--unlike options, which need to be expanded at
    # execution--so they can be used in key bindings.
    #
    # Define the root menu entrypoint as an alias:
    #  - It must be defined after the root menu so it can be expanded
    #  - Aliases can't reference other aliases, so we expand the @wk_cmd_show
    #  option as a format instead
    #  - We don't define it as an option because bind-key doesn't support
    #  formats and `run-shell "bind-key ${...}"` doesn't preserve quotes
    #  correctly
    '''
#
# Macros
#

set -gF @wk_cmd_show \\
"display-menu \\
-x '#{{@wk_cfg_pos_x}}' \\
-y '#{{@wk_cfg_pos_y}}' \\
-T '#[#{{@wk_cfg_title_style}}]#[#{{@wk_cfg_title_prefix_style}}]#{{@wk_cfg_title_prefix}}#[#{{@wk_cfg_title_style}}]'"

{macros}

#
# Keybindings
#

{keybindings}

display -p '[tmux-which-key] Done'
''')


def add_quotes(s: str) -> str:
    '''Wraps s in quotes if it has any whitespace or special chars, escaping
    existing double-quotes.'''
    if all(_is_safe_char(c) for c in s):
        return s

    return quote_tmux_string(s)


@dataclass
class Keybindings(object):
    prefix_table: str
    root_table: str = ''

    def __post_init__(self):
        if not isinstance(self.prefix_table, str):
            raise ConfigError('keybindings.prefix_table must be a string')
        if not isinstance(self.root_table, str):
            raise ConfigError('keybindings.root_table must be a string')
        if not self.prefix_table:
            raise ConfigError('keybindings.prefix_table is required')

    def __str__(self) -> str:
        return '\n\n'.join(['\n'.join(
            [
                'display -p {}'.format(quote_tmux_string(
                    '[tmux-which-key] Binding {} table key to {} ...'.format(table, key)
                )),
                'bind-key -T{} {} show-wk-menu-root'.format(table, add_quotes(key))
            ] + self._prefix_collision_warning(table, key)
        ) for table, key in [
            ('root', self.root_table),
            ('prefix', self.prefix_table),
        ] if key])

    @staticmethod
    def _prefix_collision_warning(table: str, key: str) -> List[str]:
        '''Warn at load time when the root-table key is also the tmux prefix.

        tmux consumes the prefix key before it ever consults the root table, so
        such a binding can never fire — the menu silently does not open on the
        key the config claims. The prefix is only known at runtime (the user may
        set it after this script is sourced, or never), so this has to be a tmux
        conditional rather than a build-time check.
        '''
        if table != 'root':
            return []

        return ['if -F {} {}'.format(
            quote_tmux_string('#{{==:#{{prefix}},{}}}'.format(key)),
            quote_tmux_string('display -p {}'.format(quote_tmux_string(
                '[tmux-which-key] Warning: root_table key {} is also the tmux '
                'prefix, so the root binding cannot fire. Change '
                'keybindings.root_table or your prefix.'.format(key)
            )))
        )]


@dataclass
class Position(object):
    x: str
    y: str

    def __post_init__(self):
        if not isinstance(self.x, str):
            raise ConfigError('position.x must be a string')
        if not isinstance(self.y, str):
            raise ConfigError('position.y must be a string')
        if self.x not in ['C', 'R', 'P', 'M', 'W']:
            raise ConfigError(
                'position.x must be one of C, R, P, M, W — got "{}"'.format(self.x)
            )
        if self.y not in ['C', 'P', 'M', 'W', 'S']:
            raise ConfigError(
                'position.y must be one of C, P, M, W, S — got "{}"'.format(self.y)
            )


@dataclass
class UserOption(object):
    name: str
    value: str

    def __str__(self) -> str:
        return 'set -g @{} {}'.format(self.name, quote_tmux_string(self.value))


@dataclass
class CustomVariable(object):
    name: str
    value: str

    def __post_init__(self):
        if not isinstance(self.name, str):
            raise ConfigError('custom variable name must be a string')
        if not isinstance(self.value, str):
            raise ConfigError('custom variable "{}" value must be a string'.format(self.name))

    def __str__(self) -> str:
        # Sets the env var as hidden (-h) so it's only available to tmux
        # processes.
        return 'setenv -h {} {}'.format(self.name, quote_tmux_string(self.value))


@dataclass
class Macro(object):
    index: int
    name: str
    commands: List[str]
    expand_formats: bool = False

    def __post_init__(self):
        if not isinstance(self.name, str):
            raise ConfigError('macro name must be a string')
        if not isinstance(self.expand_formats, bool):
            raise ConfigError('macro "{}" expand_formats must be a boolean'.format(self.name))
        if not all(_is_safe_char(c) for c in self.name):
            raise ConfigError('macro has invalid name: "{}". Names must be alphanumeric with - or _'.format(self.name))
        if not isinstance(self.commands, list):
            raise ConfigError('macro "{}" must have a commands list'.format(self.name))
        if not all(isinstance(c, str) for c in self.commands):
            raise ConfigError('macro "{}" commands must be strings'.format(self.name))

    def __str__(self) -> str:
        option = 'set -gF' if self.expand_formats else 'set -g'
        return '{} command-alias[{}] {}={}'.format(
            option, self.index, self.name, quote_tmux_string(' ; '.join(self.commands)),
        )


@dataclass
class MenuItem(object):
    parent_menu_id: Optional[str] = None
    name: Optional[str] = None
    key: Optional[str] = None
    menu: Optional[List[dict]] = None
    macro: Optional[str] = None
    command: Optional[str] = None
    separator: Optional[bool] = False
    transient: bool = False

    def __post_init__(
            self,
    ):
        if not isinstance(self.separator, bool):
            raise ConfigError('item "{}" separator must be a boolean'.format(self.name))
        if not isinstance(self.transient, bool):
            raise ConfigError('item "{}" transient must be a boolean'.format(self.name))
        if self.name is not None and not isinstance(self.name, str):
            raise ConfigError('item name must be a string')
        if self.key is not None and not isinstance(self.key, str):
            raise ConfigError('item "{}" key must be a string'.format(self.name))
        if self.menu is not None and not isinstance(self.menu, list):
            raise ConfigError('item "{}" menu must be a list'.format(self.name))
        if self.macro is not None and not isinstance(self.macro, str):
            raise ConfigError('item "{}" macro must be a string'.format(self.name))
        if self.command is not None and not isinstance(self.command, str):
            raise ConfigError('item "{}" command must be a string'.format(self.name))

        if not self.separator:
            if not self.name:
                raise ConfigError('item is missing a name')
            self.name = add_quotes(self.name)

            if not self.key:
                raise ConfigError('item "{}" is missing a key'.format(self.name))
            # Escape special key characters. `~` is the only one so far: tmux
            # tilde-expands an unquoted ~ while parsing, so it must be escaped
            # and quoted. Handle any future special key chars here.
            if '~' in self.key:
                self.key = '"{}"'.format(self.key.replace('~', '\\~'))

        # Check separator first: a separator carrying a command/macro/menu would
        # otherwise fall into those branches and be silently rendered as a bare
        # separator (dropping the extra field).
        if self.separator:
            if self.key or self.menu or self.macro or self.command or self.transient:
                raise ConfigError('separator items must not have other fields')
        elif self.menu:
            if not self.name or self.macro or self.command:
                raise ConfigError('submenu item must have only a name, key, and menu')
            if len(self.menu) == 0:
                raise ConfigError('submenu "{}" has no items'.format(self.name))
            # Assign an alphanumeric menu ID for use in tmux user options.
            self.menu_id = ''.join(
                [c for c in self.name if _is_safe_char(c)]).lower()
            self.command = 'show-wk-menu #{{@wk_menu_{}}}'.format(
                self.menu_id)
        elif self.macro:
            if self.menu or self.command:
                raise ConfigError('item "{}" must have only one of: menu, macro, command'.format(self.name))
            self.command = self.macro
        elif self.command:
            if self.menu or self.macro:
                raise ConfigError('item "{}" must have only one of: menu, macro, command'.format(self.name))
        else:
            raise ConfigError('item "{}" must have one of: menu, macro, command'.format(self.name))

        if self.transient:
            if not self.parent_menu_id:
                raise ConfigError('transient item "{}" has no parent menu'.format(self.name))
            self.command = '{} ; show-wk-menu #{{@wk_menu_{}}}'.format(
                self.command, self.parent_menu_id)

        if self.command:
            self.command = add_quotes(self.command)

    def __str__(self) -> str:
        if self.separator:
            return '""'

        return '{} {} {}'.format(self.name, self.key, self.command)


@dataclass
class Menu(object):
    name: str
    id: str
    items: List[MenuItem]

    def __str__(self) -> str:
        return "set -g @wk_menu_{} {}".format(
            self.id, quote_tmux_string(' '.join(map(str, self.items)))
        )


class Config(object):
    def __init__(
        self,
        command_alias_start_index: int,
        keybindings: dict,
        items: List[dict],
        title: Optional[dict] = None,
        position: Optional[dict] = None,
        custom_variables: Optional[List[dict]] = None,
        macros: Optional[List[dict]] = None,
    ) -> None:
        if not isinstance(command_alias_start_index, int):
            raise ConfigError('command_alias_start_index must be an integer')
        if command_alias_start_index < 200:
            raise ConfigError(
                'command_alias_start_index must be >= 200 (got {}). '
                'Indices 100-199 are reserved by tmux examples.'.format(command_alias_start_index)
            )
        self.command_alias_start_index = command_alias_start_index

        keybindings = require_mapping(keybindings, 'keybindings')
        reject_unknown_fields(keybindings, 'keybindings', ['prefix_table', 'root_table'])
        title = title or {}
        title = require_mapping(title, 'title')
        reject_unknown_fields(title, 'title', ['style', 'prefix', 'prefix_style'])
        title = {
            'style': title.get('style', 'align=centre,bold'),
            'prefix': title.get('prefix', 'tmux'),
            'prefix_style': title.get('prefix_style', 'fg=green,align=centre,bold'),
        }
        position = position or {'x': 'R', 'y': 'P'}
        position = require_mapping(position, 'position')
        reject_unknown_fields(position, 'position', ['x', 'y'])
        custom_variables = custom_variables or []
        macros = macros or []

        self.keybindings = Keybindings(**keybindings)
        self.title = title
        self.position = Position(**position)

        opts = {
            'wk_cfg_title_style': title['style'],
            'wk_cfg_title_prefix': title['prefix'],
            'wk_cfg_title_prefix_style': title['prefix_style'],
            'wk_cfg_pos_x': self.position.x,
            'wk_cfg_pos_y': self.position.y,
        }
        self.user_options = [UserOption(name=k, value=v)
                             for k, v in opts.items() if v]

        if not isinstance(custom_variables, list):
            raise ConfigError('custom_variables must be a list')
        custom_variables_data = []
        for i, v in enumerate(custom_variables):
            path = 'custom_variables[{}]'.format(i)
            v = require_mapping(v, path)
            require_fields(v, path, ['name', 'value'])
            reject_unknown_fields(v, path, ['name', 'value'])
            custom_variables_data.append(v)
        self.custom_variables = [CustomVariable(
            v['name'], v['value']) for v in custom_variables_data]

        if not isinstance(macros, list):
            raise ConfigError('macros must be a list')
        macro_names = set()
        for i, m in enumerate(macros):
            path = 'macros[{}]'.format(i)
            m = require_mapping(m, path)
            require_fields(m, path, ['name', 'commands'])
            reject_unknown_fields(m, path, ['name', 'commands', 'expand_formats'])
            if m.get('name') in reserved_macro_names:
                raise ConfigError(
                    'macro name "{}" is reserved by the plugin. '
                    'Reserved names: {}'.format(
                        m['name'], ', '.join(reserved_macro_names))
                )
            if m.get('name') in macro_names:
                raise ConfigError('duplicate macro name "{}"'.format(m['name']))
            macro_names.add(m.get('name'))

        macros = [{
            'name': 'show-wk-menu',
            'commands': ['#{@wk_cmd_show}'],
            'expand_formats': True,
        }, {
            'name': 'show-wk-menu-root',
            'commands': ['#{@wk_cmd_show} #{@wk_menu_root}'],
            'expand_formats': True,
        }] + macros
        self.macros = [Macro(
            self.command_alias_start_index+i,
            name=m['name'],
            commands=m['commands'],
            expand_formats=m.get('expand_formats', False),
        )
                       for i, m in enumerate(macros)]

        self.macro_names = {m.name for m in self.macros}
        self.menu_ids = set()
        self.menus = []
        self.register_menu('root', 'root', items)

    def register_menu(self, name: str, id: str, items: List[dict]):
        if not isinstance(items, list):
            raise ConfigError('menu "{}" items must be a list'.format(name))
        menu = Menu(name, id, items=[])
        if menu.id in self.menu_ids:
            raise ConfigError(
                'menu ID collision: "{}" and another menu both produce the ID "{}". '
                'Rename one of them.'.format(name, menu.id)
            )
        self.menu_ids.add(menu.id)

        mapped_keys = set()
        for i, item in enumerate(items):
            item_path = 'menu "{}" item {}'.format(name, i)
            item = require_mapping(item, item_path)
            reject_unknown_fields(item, item_path, [
                'name', 'key', 'menu', 'macro', 'command', 'separator', 'transient',
            ])
            item = MenuItem(parent_menu_id=id, **item)
            if item.menu:
                assert item.name
                self.register_menu(item.name, item.menu_id, item.menu)
            elif item.macro:
                if item.macro not in self.macro_names:
                    raise ConfigError(
                        'item "{}" references unknown macro "{}". '
                        'Defined macros: {}'.format(item.name, item.macro, ', '.join(sorted(self.macro_names)))
                    )

            if item.key:
                if item.key in mapped_keys:
                    raise ConfigError(
                        'duplicate key "{}" in menu "{}"'.format(item.key, name)
                    )
            mapped_keys.add(item.key)

            menu.items.append(item)

        self.menus.append(menu)
        return menu

    def __str__(self) -> str:
        return template.format(
            user_options='\n'.join(map(str, self.user_options)),
            custom_variables='\n'.join(map(str, self.custom_variables)),
            menus='\n\n'.join(map(str, self.menus)),
            macros='\n\n'.join(map(str, self.macros)),
            keybindings=self.keybindings,
        )


def main() -> int:
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "config_file", help="The plugin config file", type=Path)
    parser.add_argument(
        "output_file", nargs='?', help="The file where plugin init script will be written", type=Path)
    parser.add_argument(
        "--validate", action="store_true",
        help="Validate config only — do not write output")
    args = parser.parse_args()

    if not args.validate and args.output_file is None:
        parser.error("output_file is required unless --validate is set")

    try:
        logging.info('Reading configuration ...')
        with open(args.config_file) as config_file:
            data = yaml.load(config_file, Loader=_DuplicateKeyLoader)
        if not isinstance(data, dict):
            raise ConfigError('config file must be a YAML mapping at the top level')

        logging.info('Building menu ...')
        config = Config(**data)

    except ConfigError as e:
        raise SystemExit('[tmux-which-key] Config error: {}'.format(e))
    except yaml.YAMLError as e:
        raise SystemExit('[tmux-which-key] Config error: invalid YAML in {}: {}'.format(
            args.config_file, e))
    except OSError as e:
        raise SystemExit('[tmux-which-key] Config error: cannot read {}: {}'.format(
            args.config_file, e))
    except TypeError as e:
        # Config(**data) raises TypeError for both missing required fields and
        # unexpected top-level fields; Python's message says which.
        raise SystemExit('[tmux-which-key] Config error: invalid top-level field(s) — {}'.format(e))

    if args.validate:
        logging.info('Config is valid')
        return 0

    out = str(config)
    with open(args.output_file, 'w') as output_file:
        output_file.write(out)

    logging.info('Done')
    return 0


if __name__ == '__main__':
    sys.exit(main())
